spring:
  application:
    name: travel-trip
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
